services:
  db:
    image: postgres:15
    container_name: parksystem_db
    environment:
      POSTGRES_USER: parksys
      POSTGRES_PASSWORD: system
      POSTGRES_DB: parksystem_db
    volumes:
      - ./db:/docker-entrypoint-initdb.d
    ports:
      - "5433:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U parksys -d parksystem_db"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: always

  backend:
    build: ./backend_go
    container_name: parksystem_backend
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "8080:8080"
    environment:
      DATABASE_HOST: db
      DATABASE_PORT: 5432
      DATABASE_USER: parksys
      DATABASE_PASSWORD: system
      DATABASE_NAME: parksystem_db
      JWT_SECRET: supersegreto
    restart: always
